### ISSUE TITLE
GWBK exploration tool

### ISSUE THREAD

**Issue by paul-griffith** [paul-griffith/kindling#19]
See what's in the GWBK, what version it came from, make changes?

Needs a compelling reason to exist.

**Comment by paul-griffith** [comment]
Export (and import?) of projects from a given .gwbk

**Comment by ryanjmclaughlin** [comment]
> Export (and import?) of projects from a given .gwbk

This!  One of the deployment topics I am constantly asked is the "rollback plan" for a project deployment.  While sometimes we take a project backup, a lot of times we don't because we know we can roll back the project via the 6 hr backups, BUT extracting a project from a gwbk is not the fastest or most user friendly thing to do.

Also, extracting a tag backup from a gwbk would be a cool use-case for recovery scenarios.

**Comment by paul-griffith** [comment]
Project extraction is available in 0.0.2; let me know if you try it out and run into any issues.

Tag extraction would be a different beast; besides getting a SQLite connection, it would require reconstructing the tags. Probably doable, but may not happen any time soon.
